
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmocats
    username: cosmocats
    password: cosmocats
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/.well-known/jwks.json

server:
  port: 8080

app:
  features:
    cosmoCats: false
    kittyProducts: false
  security:
    bot-key: "cosmos-cat-bot-secret-x99" # Ключ для розробки та тестувань, в реальному продукті приховати його
